name: YouTrack Issue Move

on:
  pull_request:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: bloobirds-it/action-youtrack-move@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yt-url: ${{ secrets.YOUTRACK_URL }}
          yt-token: ${{ secrets.YOUTRACK_TOKEN }}
          yt-column-field: "Состояние"
          yt-project-id: "HANDS"
          yt-column-triggers: "в процессе"
          yt-column-target: "в ревью"
